/** Maps static Arabic frontend copy to i18n keys. Unmapped values (names) pass through. */
const KNOWN: Record<string, string> = {
  "مركز خطوة للتأهيل": "copy.centerKhatwa",
  "مركز كيان": "copy.centerKayan",
  "مركز فنون": "copy.centerFunoon",
  "مركز تنمية الطفل": "copy.centerChildDev",
  "مركز الأمل للتنمية": "copy.centerAmalDev",
  "مركز نور الحياة": "copy.centerNoor",
  "مركز بداية": "copy.centerBidaya",
  "مدرسة النور للتربية الخاصة": "copy.schoolNoor",
  "مدرسة الأمل الشاملة": "copy.schoolAmal",
  "مدرسة البيان الخاصة": "copy.schoolBayan",
  "مدرسة التميز العالمية": "copy.schoolTamayoz",
  "مدرسة الكويت للصم": "copy.schoolDeaf",
  "العلاج الوظيفي": "copy.ot",
  "العلاج الطبيعي": "copy.pt",
  "التدخل المبكر": "copy.earlyIntervention",
  "النطق والتخاطب": "copy.speech",
  "التوحد": "copy.autism",
  "العلاج السلوكي": "copy.behavioral",
  "اختصاصية نفسية": "copy.psychologistF",
  "استشاري أطفال": "copy.pediatricConsultant",
  "اختصاصية نطق ولغة": "copy.slpF",
  "استشاري أعصاب": "copy.neuroConsultant",
  "أخصائي علاج وظيفي": "copy.otSpecialist",
  "استشارية تغذية": "copy.nutritionConsultantF",
  "أخصائي سلوكي": "copy.behaviorSpecialist",
  "حولي": "copy.hawalli",
  "الفروانية": "copy.farwaniya",
  "الجهراء": "copy.jahra",
  "العاصمة": "copy.capital",
  "التربية الخاصة": "copy.specialEducation",
  "الشاملة": "copy.inclusive",
  "الخاصة": "copy.privateBranch",
  "العالمية": "copy.international",
  "الصم": "copy.deaf",
  "صعوبات التعلم": "copy.learningDifficulties",
  "التعليم الشامل": "copy.inclusiveEducation",
  "منهج عالمي": "copy.internationalCurriculum",
  "الإعاقة السمعية": "copy.hearingDisability",
  "3 - 18 سنة": "copy.age3to18",
  "ابتدائي - ثانوي": "copy.primarySecondary",
  "7:30 ص - 1:30 م": "copy.schoolHours",
  "تقدم تعليماً متخصصاً وشاملاً للأطفال من ذوي الاحتياجات الخاصة، مع بيئة آمنة ومحفزة وبرامج تربوية متخصصة.":
    "copy.schoolAbout",
  "تقدم تعليماً متخصصاً وشاملاً للأطفال من ذوي الاحتياجات الخاصة، مع بيئة آمنة ومحفزة وبرامج تربوية متخصصة":
    "copy.schoolAbout",
  "كرسي متحرك": "copy.wheelchair",
  "بطاقات تواصل مصورة": "copy.pictureCards",
  "سماعات عازلة للضوضاء": "copy.noiseCancelling",
  "أدوات تنمية مهارات": "copy.skillTools",
  "لوحة تواصل": "copy.communicationBoard",
  "وسادة دعم": "copy.supportCushion",
  "مكعبات حسية": "copy.sensoryBlocks",
  "حزام أمان": "copy.safetyBelt",
  "أدوات تعليمية": "copy.educationalTools",
  "المستلزمات": "copy.supplies",
  "زراعية": "copy.agricultural",
  "التنظيف": "copy.cleaning",
  "تعليم": "copy.educationCat",
  "رعاية": "copy.careCat",
  "معلمة منزلية خاصة": "copy.privateHomeTeacher",
  "ممرضة منزلية": "copy.homeNurse",
  "أخصائية علاج طبيعي": "copy.homePt",
  "مساعدة منزلية مدربة": "copy.trainedHomeAide",
  "عاملة تنظيف منزلية": "copy.homeCleaner",
  "خدمات تنظيف منزلية": "copy.homeCleaningServices",
  "خدمات زراعية منزلية": "copy.homeGardenServices",
  "مساعدة زراعية منزلية": "copy.homeGardenAide",
  تواصل: "copy.tagCommunication",
  سلوكي: "copy.tagBehavior",
  حسي: "copy.tagSensory",
  "تأخر نمائي": "copy.tagDelay",
  "طيف التوحد": "copy.tagAutism",
  "فرط الحركة": "copy.tagAdhd",
  "تمرين النطق": "copy.speechExercise",
  "تكرار كلمات بسيطة لمدة 10 دقائق": "copy.speechExerciseDesc",
  "لعب تفاعلي": "copy.interactivePlay",
  "لعبة تبادل الأدوار مع الوالدين": "copy.interactivePlayDesc",
  "نشاط حسي": "copy.sensoryActivity",
  "تمرين حسي لليدين باستخدام الرمل": "copy.sensoryActivityDesc",
  "سيتم المحاولة غداً": "copy.tryTomorrow",
  "مفيد جداً": "copy.veryHelpful",
  مفيد: "copy.helpful",
  "عيادة علاج النطق": "copy.speechClinic",
  "الأحد ٢٠ سبتمبر": "copy.demoApptDate",
  "٤:٠٠ م": "copy.demoApptTime",
  "موعد طبيب تجريبي": "copy.demoApptNotes",
  "تحسين التواصل اليومي، تعزيز اللعب التفاعلي، وتنظيم الاستجابة الحسية خلال الأسبوع.":
    "copy.demoGoals",
  "تحسين مهارات التواصل، وزيادة التركيز على المهام اليومية، وتعزيز الاستقلالية.":
    "copy.demoGoalsSkills",
  "التمرين لمدة 10 دقائق": "copy.speechMins10",
  "اللعب بالمكعبات لمدة 15 دقيقة": "copy.playBlocks15",
  "استخدام كرة الضغط لمدة 5 دقائق": "copy.pressureBall5",
  "كان متعب اليوم": "copy.wasTiredToday",
  "د. أحمد – علاج وظيفي": "copy.demoOtDoctor",
  "الأحد 20 سبتمبر": "copy.demoApptDateSun20",
  "5:00 مساءً": "copy.demoApptTime5pm",
  "العلاج السلوكي": "copy.homeTherapyBehavioral",
  "العلاج الوظيفي": "copy.homeTherapyOccupational",
  "علاج النطق": "copy.homeTherapySpeech",
  "مؤسسة فاطمة": "copy.fatimaOrg",
};

export function knownText(t: (key: string) => string, value?: string | null): string {
  if (!value) return "";
  const key = KNOWN[value];
  return key ? t(key) : value;
}
